vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: '%app.images.base_url%'
            upload_destination: '%kernel.project_dir%/public/%app.images.base_url%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        audio:
            uri_prefix: '%app.audio.base_url%'
            upload_destination: '%kernel.project_dir%/public%app.audio.base_url%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
